import type { ServiceContract, SchemaDescriptor } from "../common/contract"
import { getDefaultLogger } from "../common/logger"

export interface GenerateOptions {
  serviceMapName?: string
  serviceName?: string
  includeMeta?: boolean
}

const SAFE_CONTRACT_TOKEN = /^[A-Za-z0-9_.@-]+$/
const SAFE_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

// Safe TS string literal: JSON.stringify escapes \, " and control chars; U+2028/9 break JS source.
function tsString(s: string): string {
  return JSON.stringify(String(s)).replaceAll("\u2028", "\\u2028").replaceAll("\u2029", "\\u2029")
}

function commentText(s: string): string {
  return String(s).replace(/[\r\n\u2028\u2029]+/g, " ")
}

function assertSafeToken(value: unknown, what: string): void {
  if (typeof value !== "string" || !SAFE_CONTRACT_TOKEN.test(value)) {
    throw new Error(`Refusing to generate: ${what} ${JSON.stringify(String(value))} contains unexpected characters`)
  }
}

function tsName(s: string): string {
  return SAFE_IDENTIFIER.test(s) ? s : tsString(s)
}

function pascalCase(s: string): string {
  return s
    .replace(/[^A-Za-z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("")
}

function schemaToTs(schema: SchemaDescriptor | null | undefined, depth = 0): string {
  if (!schema) return "unknown"
  if (depth > 10) return "unknown"
  if (schema.kind === "class-validator") return schema.className && SAFE_IDENTIFIER.test(schema.className) ? schema.className : "unknown"
  if (schema.kind === "json-schema") return "unknown"
  if (schema.kind === "unknown") return "unknown"
  if (schema.kind === "zod") return zodShapeToTs(schema.shape, depth)
  return "unknown"
}

function zodShapeToTs(node: any, depth: number): string {
  if (!node || typeof node !== "object") return "unknown"
  switch (node.type) {
    case "string":
      return "string"
    case "number":
      return "number"
    case "bigint":
      return "bigint"
    case "boolean":
      return "boolean"
    case "date":
      return "Date"
    case "literal":
      if (typeof node.value === "string") return tsString(node.value)
      return JSON.stringify(node.value)
    case "enum":
      return (node.values as unknown[]).map((v) => (typeof v === "string" ? tsString(v) : JSON.stringify(v))).join(" | ") || "unknown"
    case "array":
      return `Array<${zodShapeToTs(node.items, depth + 1)}>`
    case "optional":
      return `${zodShapeToTs(node.inner, depth + 1)} | undefined`
    case "nullable":
      return `${zodShapeToTs(node.inner, depth + 1)} | null`
    case "union":
      return (node.options || []).map((o: any) => zodShapeToTs(o, depth + 1)).join(" | ") || "unknown"
    case "intersection":
      return `(${zodShapeToTs(node.left, depth + 1)}) & (${zodShapeToTs(node.right, depth + 1)})`
    case "record":
      return `Record<string, ${zodShapeToTs(node.valueType, depth + 1)}>`
    case "tuple": {
      const items = (node.items ?? []).map((it: any) => zodShapeToTs(it, depth + 1))
      if (node.rest) items.push(`...Array<${zodShapeToTs(node.rest, depth + 1)}>`)
      return `[${items.join(", ")}]`
    }
    case "map":
      return `Map<${zodShapeToTs(node.keyType, depth + 1)}, ${zodShapeToTs(node.valueType, depth + 1)}>`
    case "set":
      return `Set<${zodShapeToTs(node.valueType, depth + 1)}>`
    case "default":
    case "effects":
    case "pipe":
      return zodShapeToTs(node.inner, depth + 1)
    case "object": {
      const fields = node.fields ?? {}
      const lines: string[] = []
      for (const [k, v] of Object.entries(fields)) {
        const ts = zodShapeToTs(v as any, depth + 1)
        const optional = isOptionalField(v)
        lines.push(`  ${tsName(k)}${optional ? "?" : ""}: ${ts}`)
      }
      return `{\n${lines.join("\n")}\n}`
    }
    default:
      getDefaultLogger().warn({ event: "codegen.zod.unhandled", kind: node?.type }, "Unhandled zod node in TS conversion; emitting unknown")
      return "unknown"
  }
}

function isOptionalField(node: any): boolean {
  return node?.type === "optional" || node?.type === "default"
}

export function generateContractModule(contract: ServiceContract, opts?: GenerateOptions): string {
  for (const m of contract.methods) {
    assertSafeToken(m.signalName, "method signalName")
    assertSafeToken(m.version, "method version")
  }
  const service = opts?.serviceName ?? contract.serviceName
  const baseName = opts?.serviceMapName ?? `${pascalCase(service)}ServiceContract`
  // Drop a trailing "ServiceContract"/"Contract" suffix, else append "Client".
  const clientName = `${baseName.replace(/(Service)?Contract$/, "")}Client`
  const generatedAtMs = Number(contract.generatedAt)

  const lines: string[] = []
  lines.push(`// Auto-generated by @riaskov/nevo-messaging — do not edit by hand`)
  lines.push(`// Service: ${commentText(contract.serviceName)}`)
  if (contract.serviceVersion) lines.push(`// Version: ${commentText(contract.serviceVersion)}`)
  lines.push(`// Generated: ${Number.isFinite(generatedAtMs) ? new Date(generatedAtMs).toISOString() : "unknown"}`)
  lines.push("")
  lines.push(`import type { TypedClient } from "@riaskov/nevo-messaging"`)
  lines.push("")
  lines.push(`export interface ${baseName} {`)

  for (const m of contract.methods) {
    const params = schemaToTs(m.paramsSchema)
    const result = schemaToTs(m.resultSchema)
    lines.push(`  ${tsName(m.signalName)}: { params: ${params}; result: ${result} }`)
  }
  lines.push(`}`)
  lines.push("")
  // Emit the typed-client alias for this service's contract.
  lines.push(`export type ${clientName} = TypedClient<${baseName}>`)
  lines.push("")
  lines.push(`export const ${pascalCase(service)}ContractMethods = [`)
  for (const m of contract.methods) {
    lines.push(`  { signalName: ${tsString(m.signalName)}, version: ${tsString(m.version)} },`)
  }
  lines.push(`] as const`)
  lines.push("")
  lines.push(`export const ${pascalCase(service)}ContractMeta = {`)
  lines.push(`  serviceName: ${tsString(contract.serviceName)},`)
  if (contract.serviceVersion) lines.push(`  serviceVersion: ${tsString(contract.serviceVersion)},`)
  lines.push(`  generatedAt: ${Number.isFinite(generatedAtMs) ? generatedAtMs : 0}`)
  lines.push(`} as const`)
  lines.push("")
  return lines.join("\n")
}
