import type { ServiceContract, SchemaDescriptor } from "../common/contract"
import { getDefaultLogger } from "../common/logger"

export interface GenerateOptions {
  serviceMapName?: string
  serviceName?: string
  includeMeta?: boolean
}

function tsName(s: string): string {
  if (!/^[A-Za-z_$]/.test(s)) return `"${s.replaceAll('"', '\\"')}"`
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s) ? s : `"${s.replaceAll('"', '\\"')}"`
}

function pascalCase(s: string): string {
  return s
    .replace(/[^A-Za-z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("")
}

function schemaToTs(schema: SchemaDescriptor | null | undefined, depth = 0): string {
  if (!schema) return "unknown"
  if (depth > 10) return "unknown"
  if (schema.kind === "class-validator") return schema.className || "unknown"
  if (schema.kind === "json-schema") return "unknown"
  if (schema.kind === "unknown") return "unknown"
  if (schema.kind === "zod") return zodShapeToTs(schema.shape, depth)
  return "unknown"
}

function zodShapeToTs(node: any, depth: number): string {
  if (!node || typeof node !== "object") return "unknown"
  switch (node.type) {
    case "string": return "string"
    case "number": return "number"
    case "bigint": return "bigint"
    case "boolean": return "boolean"
    case "date": return "Date"
    case "literal":
      if (typeof node.value === "string") return `"${node.value.replaceAll('"', '\\"')}"`
      return JSON.stringify(node.value)
    case "enum":
      return (node.values as unknown[]).map((v) => (typeof v === "string" ? `"${v}"` : JSON.stringify(v))).join(" | ") || "unknown"
    case "array":
      return `Array<${zodShapeToTs(node.items, depth + 1)}>`
    case "optional":
      return `${zodShapeToTs(node.inner, depth + 1)} | undefined`
    case "nullable":
      return `${zodShapeToTs(node.inner, depth + 1)} | null`
    case "union":
      return (node.options || []).map((o: any) => zodShapeToTs(o, depth + 1)).join(" | ") || "unknown"
    case "intersection":
      return `(${zodShapeToTs(node.left, depth + 1)}) & (${zodShapeToTs(node.right, depth + 1)})`
    case "record":
      return `Record<string, ${zodShapeToTs(node.valueType, depth + 1)}>`
    case "tuple": {
      const items = (node.items ?? []).map((it: any) => zodShapeToTs(it, depth + 1))
      if (node.rest) items.push(`...Array<${zodShapeToTs(node.rest, depth + 1)}>`)
      return `[${items.join(", ")}]`
    }
    case "map":
      return `Map<${zodShapeToTs(node.keyType, depth + 1)}, ${zodShapeToTs(node.valueType, depth + 1)}>`
    case "set":
      return `Set<${zodShapeToTs(node.valueType, depth + 1)}>`
    case "default":
    case "effects":
    case "pipe":
      return zodShapeToTs(node.inner, depth + 1)
    case "object": {
      const fields = node.fields ?? {}
      const lines: string[] = []
      for (const [k, v] of Object.entries(fields)) {
        const ts = zodShapeToTs(v as any, depth + 1)
        const optional = isOptionalField(v)
        lines.push(`  ${tsName(k)}${optional ? "?" : ""}: ${ts}`)
      }
      return `{\n${lines.join("\n")}\n}`
    }
    default:
      getDefaultLogger().warn({ event: "codegen.zod.unhandled", kind: node?.type }, "Unhandled zod node in TS conversion; emitting unknown")
      return "unknown"
  }
}

function isOptionalField(node: any): boolean {
  return node?.type === "optional" || node?.type === "default"
}

export function generateContractModule(contract: ServiceContract, opts?: GenerateOptions): string {
  const service = opts?.serviceName ?? contract.serviceName
  const baseName = opts?.serviceMapName ?? `${pascalCase(service)}ServiceContract`
  // Client alias name: drop a trailing "ServiceContract"/"Contract" suffix so
  // `FooServiceContract` -> `FooClient`; otherwise just append "Client".
  const clientName = `${baseName.replace(/(Service)?Contract$/, "")}Client`

  const lines: string[] = []
  lines.push(`// Auto-generated by @riaskov/nevo-messaging — do not edit by hand`)
  lines.push(`// Service: ${contract.serviceName}`)
  if (contract.serviceVersion) lines.push(`// Version: ${contract.serviceVersion}`)
  lines.push(`// Generated: ${new Date(contract.generatedAt).toISOString()}`)
  lines.push("")
  lines.push(`import type { TypedClient } from "@riaskov/nevo-messaging"`)
  lines.push("")
  lines.push(`export interface ${baseName} {`)

  for (const m of contract.methods) {
    const params = schemaToTs(m.paramsSchema)
    const result = schemaToTs(m.resultSchema)
    const sig = m.signalName.includes("@") ? m.signalName : `${m.signalName}`
    lines.push(`  ${tsName(sig)}: { params: ${params}; result: ${result} }`)
  }
  lines.push(`}`)
  lines.push("")
  // Typed facade over a transport client, scoped to this service's contract.
  // `typed<${baseName}>(client)` returns an instance whose `query`/`emit` infer
  // params & result from the interface above.
  lines.push(`export type ${clientName} = TypedClient<${baseName}>`)
  lines.push("")
  lines.push(`export const ${pascalCase(service)}ContractMethods = [`)
  for (const m of contract.methods) {
    lines.push(`  { signalName: "${m.signalName}", version: "${m.version}" },`)
  }
  lines.push(`] as const`)
  lines.push("")
  lines.push(`export const ${pascalCase(service)}ContractMeta = {`)
  lines.push(`  serviceName: "${contract.serviceName}",`)
  if (contract.serviceVersion) lines.push(`  serviceVersion: "${contract.serviceVersion}",`)
  lines.push(`  generatedAt: ${contract.generatedAt}`)
  lines.push(`} as const`)
  lines.push("")
  return lines.join("\n")
}
