services:
  kafka:
    image: apache/kafka:4.0.0
    hostname: kafka
    ports:
      - "127.0.0.1:9092:9092"
      - "127.0.0.1:9094:9094"
    volumes:
      - "./kafka-data:/opt/kafka/data"
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL://kafka:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_LOG_DIRS=/opt/kafka/data
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - CLUSTER_ID=YkU3OEVBNTcwNTJENDM2QY
      - KAFKA_LOG4J_ROOT_LOGLEVEL=ERROR
      - KAFKA_LOG4J_LOGGERS=org.apache.kafka=ERROR,kafka=ERROR,kafka.cluster.Partition=ERROR
      - KAFKA_NUM_PARTITIONS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS=2000
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=30000
      - KAFKA_SOCKET_RECEIVE_BUFFER_BYTES=102400
      - KAFKA_SOCKET_SEND_BUFFER_BYTES=102400
      - KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES=102400
      - KAFKA_REPLICA_SOCKET_SEND_BUFFER_BYTES=102400
      - KAFKA_CONNECTIONS_MAX_IDLE_MS=30000
      - KAFKA_NUM_NETWORK_THREADS=3
      - KAFKA_NUM_IO_THREADS=8
    restart: on-failure

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "127.0.0.1:8084:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9094
    restart: on-failure
    depends_on:
      - kafka

networks:
  kafka-net:
    driver: bridge
