export const DEFAULT_SUBSCRIPTION_SUFFIX = "-events.sub"
export const DEFAULT_EVENTS_SUFFIX = "-events"
export const DEFAULT_BROADCAST_TOPIC = "__broadcast"
export const DEFAULT_DISCOVERY_TOPIC = "__nevo.discovery"
export const DEFAULT_REPLY_SUFFIX = ".reply"
export const NEVO_PROTOCOL_VERSION = "1"
